import { GoogleGenAI, Modality } from "@google/genai";
import type { EditControls } from "../types";
import { INITIAL_CONTROLS } from "../constants";

export const buildPrompt = (controls: EditControls): string => {
    const prompts: string[] = [];

    const getEnglishTerm = (value: string): string => {
        const match = value.match(/\(([^)]+)\)/);
        return match ? match[1] : value;
    };

    if (controls.objectRotation !== INITIAL_CONTROLS.objectRotation) {
        prompts.push(`Set the main object's orientation to: '${getEnglishTerm(controls.objectRotation)}'.`);
    }
    if (controls.cameraUpDown !== INITIAL_CONTROLS.cameraUpDown) {
        const englishValue = getEnglishTerm(controls.cameraUpDown); // e.g., "Up 25°" or "Down 45°"
        const angleMatch = englishValue.match(/(\d+)/);
        if (angleMatch) {
            const angle = angleMatch[1];
            if (parseInt(angle, 10) > 0) { // Only add prompt if angle is not 0
                // 'from above' = looking down. 'from below' = looking up.
                const direction = englishValue.includes('Up') ? 'from below' : 'from above';
                prompts.push(`Adjust the camera angle to be ${angle} degrees ${direction}.`);
            }
        }
    }
    if (controls.cameraRotation !== INITIAL_CONTROLS.cameraRotation) {
        prompts.push(`Rotate the camera view horizontally by ${controls.cameraRotation} degrees.`);
    }
    if (controls.zoom !== INITIAL_CONTROLS.zoom) {
        const zoomDirection = controls.zoom > 0 ? 'in' : 'out';
        prompts.push(`Zoom ${zoomDirection} by a factor of ${Math.abs(controls.zoom)}x.`);
    }
    if (controls.handGesture !== INITIAL_CONTROLS.handGesture) {
        prompts.push(`Change the primary person's hand gesture to: '${getEnglishTerm(controls.handGesture)}'.`);
    }
    if (controls.feetGesture !== INITIAL_CONTROLS.feetGesture) {
        prompts.push(`Change the primary person's feet position to: '${getEnglishTerm(controls.feetGesture)}'.`);
    }
    if (controls.bodyPose !== INITIAL_CONTROLS.bodyPose) {
        prompts.push(`Change the primary person's body pose to: '${getEnglishTerm(controls.bodyPose)}'.`);
    }
    if (controls.prompt.trim()) {
        prompts.push(`Apply this custom instruction: "${controls.prompt.trim()}".`);
    }

    if (prompts.length === 0) {
        return "Re-render the image with higher quality. Preserve the original aspect ratio.";
    }

    let basePrompt = "Edit the image with the following instructions: " + prompts.join(' ');
    
    if (controls.lockAspectRatio) {
        basePrompt += " It is crucial that you preserve the original aspect ratio of the image.";
    }

    return basePrompt;
};

export const editImageWithControls = async (
    base64ImageData: string,
    mimeType: string,
    controls: EditControls
): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable not set");
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const promptText = buildPrompt(controls);

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64ImageData,
                        mimeType: mimeType,
                    },
                },
                {
                    text: promptText,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API.");
};
